name: Run my python
on:
    push:

jobs:
    build:
        name: do job1p
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run test py
          run: 
            python3 test.py 

    build2:
        name: do job2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run test2 py
              run:
                python3 test2.py

                         